-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 09/04/2021 08:44:29
-- Server version: 5.6.20
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE tutorial_api;

--
-- Definition for table migrations
--
DROP TABLE IF EXISTS migrations;
CREATE TABLE migrations (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  migration VARCHAR(255) NOT NULL,
  batch INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

--
-- Definition for table tutorials
--
DROP TABLE IF EXISTS tutorials;
CREATE TABLE tutorials (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  user_id INT(10) UNSIGNED NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

--
-- Definition for table users
--
DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  updated_at DATETIME DEFAULT NULL,
  created_at DATETIME DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

--
-- Definition for table usersxx
--
DROP TABLE IF EXISTS usersxx;
CREATE TABLE usersxx (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table migrations
--

-- Table tutorial_api.migrations does not contain any data (it is empty)

-- 
-- Dumping data for table tutorials
--

-- Table tutorial_api.tutorials does not contain any data (it is empty)

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'triono', 'triono.triono1@gmail.com', '$2y$10$GrH6lDnzZNeEKx.0aY4/MezwBl4G.R6TFr8KqGbGHNiOlHwRG7kBS', '2020-06-24 16:39:15', '2020-06-24 16:39:15');

-- 
-- Dumping data for table usersxx
--

-- Table tutorial_api.usersxx does not contain any data (it is empty)

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;